# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
# - task: NuGetToolInstaller@1

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '**/*.sln'

# - task: XamarinAndroid@1
#   inputs:
#     projectFile: '**/*droid*.csproj'
#     outputDirectory: '$(outputDirectory)'
#     configuration: '$(buildConfiguration)'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $VariableGroupId = 6
      $NewValue = 10
      $VariableName = "versionCode"
      
      Write-Host "NewValue : $NewValue"
      $url = "$($env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI)$env:SYSTEM_TEAMPROJECTID/_apis/distributedtask/variablegroups/$($VariableGroupId)?api-version=5.1-preview.1"
      Write-Host "URL: $url"
      $authHeader = @{Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN" }
      Write-Host "Bearer: $env:SYSTEM_ACCESSTOKEN"
      $definition = Invoke-RestMethod -Uri $url -Headers $authHeader
      Write-Host "Pipeline = $($definition | ConvertTo-Json -Depth 100)"
      $definition.variables.$VariableName.Value = "$($NewValue)"
      $definitionJson = $definition | ConvertTo-Json -Depth 100 -Compress
      Invoke-RestMethod -Method Put -Uri $url -Headers $authHeader -ContentType "application/json" -Body ([System.Text.Encoding]::UTF8.GetBytes($definitionJson)) | Out-Null